name: ocp-models
channels:
  - pytorch
  - pyg
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=1.4.0=pyhd8ed1ab_0
  - aiohttp=3.8.5=py39hd1e30aa_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alsa-lib=1.2.10=hd590300_0
  - anyio=3.5.0=py39h06a4308_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py39h7f8727e_0
  - ase=3.22.1=pyhd8ed1ab_1
  - asttokens=2.4.0=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_1
  - attrs=23.1.0=pyh71513ae_1
  - babel=2.11.0=py39h06a4308_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - black=22.3.0=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.6.2=pyhd8ed1ab_0
  - boto3=1.28.46=pyhd8ed1ab_0
  - botocore=1.31.46=pyhd8ed1ab_0
  - brotli=1.1.0=hd590300_0
  - brotli-bin=1.1.0=hd590300_0
  - brotlipy=0.7.0=py39hb9d737c_1005
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.08.22=h06a4308_0
  - cachetools=5.3.1=pyhd8ed1ab_0
  - cairo=1.16.0=h0c91306_1017
  - certifi=2023.11.17=py39h06a4308_0
  - cffi=1.15.1=py39he91dace_3
  - cfgv=3.3.1=pyhd8ed1ab_0
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - colored=1.4.4=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - contourpy=1.1.0=py39h7633fee_0
  - cryptography=41.0.3=py39hd4f0224_0
  - cuda=11.6.1=0
  - cuda-cccl=11.6.55=hf6102b2_0
  - cuda-command-line-tools=11.6.2=0
  - cuda-compiler=11.6.2=0
  - cuda-cudart=11.6.55=he381448_0
  - cuda-cudart-dev=11.6.55=h42ad0f4_0
  - cuda-cuobjdump=11.6.124=h2eeebcb_0
  - cuda-cupti=11.6.124=h86345e5_0
  - cuda-cuxxfilt=11.6.124=hecbf4f6_0
  - cuda-driver-dev=11.6.55=0
  - cuda-gdb=12.2.140=0
  - cuda-libraries=11.6.1=0
  - cuda-libraries-dev=11.6.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=12.2.144=0
  - cuda-nsight-compute=12.2.2=0
  - cuda-nvcc=11.6.124=hbba6d2d_0
  - cuda-nvdisasm=12.2.140=0
  - cuda-nvml-dev=11.6.55=haa9ef22_0
  - cuda-nvprof=12.2.142=0
  - cuda-nvprune=11.6.124=he22ec0a_0
  - cuda-nvrtc=11.6.124=h020bade_0
  - cuda-nvrtc-dev=11.6.124=h249d397_0
  - cuda-nvtx=11.6.124=h0630a44_0
  - cuda-nvvp=12.2.142=0
  - cuda-runtime=11.6.1=0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=12.2.140=0
  - cuda-toolkit=11.6.1=0
  - cuda-tools=11.6.1=0
  - cuda-visual-tools=11.6.1=0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.0=py39h3d6467e_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distlib=0.3.7=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - e3nn=0.4.4=pyhd8ed1ab_1
  - emmet-core=0.68.0=pyhd8ed1ab_0
  - entrypoints=0.4=py39h06a4308_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - filelock=3.12.3=pyhd8ed1ab_0
  - flask=2.3.3=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.42.1=py39hd1e30aa_0
  - freetype=2.12.1=hca18f0e_1
  - frozenlist=1.4.0=py39hd1e30aa_0
  - future=0.18.3=pyhd8ed1ab_0
  - gds-tools=1.7.2.10=0
  - gettext=0.21.1=h27087fc_0
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.36=pyhd8ed1ab_0
  - glib=2.78.0=hfc55251_0
  - glib-tools=2.78.0=hfc55251_0
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.2=py39h376b7d2_1
  - google-auth=2.23.0=pyh1a96a4e_0
  - google-auth-oauthlib=1.0.0=pyhd8ed1ab_1
  - graphite2=1.3.13=h58526e2_1001
  - grpcio=1.57.0=py39h174d805_1
  - gst-plugins-base=1.22.5=h8e1006c_1
  - gstreamer=1.22.5=h98fc4e7_1
  - harfbuzz=8.2.0=h3d44ed6_0
  - icu=73.2=h59595ed_0
  - identify=2.5.28=pyhd8ed1ab_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib-resources=6.0.1=pyhd8ed1ab_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.0.1=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - ipykernel=6.25.2=pyh2140261_0
  - ipython=8.15.0=pyh0d859eb_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=8.0.4=py39h06a4308_0
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jedi=0.19.0=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jmespath=1.0.1=pyhd8ed1ab_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.17.3=py39h06a4308_0
  - jupyter=1.0.0=py39h06a4308_8
  - jupyter_client=7.4.9=py39h06a4308_0
  - jupyter_console=6.6.3=py39h06a4308_0
  - jupyter_core=5.3.1=py39hf3d152e_0
  - jupyter_server=1.13.5=pyhd3eb1b0_0
  - jupyterlab=3.3.2=pyhd3eb1b0_0
  - jupyterlab_server=2.10.3=pyhd3eb1b0_1
  - jupyterlab_widgets=3.0.5=py39h06a4308_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py39h7633fee_0
  - krb5=1.21.2=h659d440_0
  - lame=3.100=h166bdaf_1003
  - latexcodec=2.0.1=pyh9f0ad1d_0
  - lcms2=2.15=haa2dc70_1
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230802.0=cxx17_h59595ed_3
  - libblas=3.9.0=16_linux64_mkl
  - libbrotlicommon=1.1.0=hd590300_0
  - libbrotlidec=1.1.0=hd590300_0
  - libbrotlienc=1.1.0=hd590300_0
  - libcap=2.69=h0f662aa_0
  - libcblas=3.9.0=16_linux64_mkl
  - libclang=15.0.7=default_h7634d5b_3
  - libclang13=15.0.7=default_h9986a30_3
  - libcublas=11.9.2.110=h5e84587_0
  - libcublas-dev=11.9.2.110=h5c901ab_0
  - libcufft=10.7.1.112=hf425ae0_0
  - libcufft-dev=10.7.1.112=ha5ce4c0_0
  - libcufile=1.7.2.10=0
  - libcufile-dev=1.7.2.10=0
  - libcups=2.3.3=h4637d8d_4
  - libcurand=10.3.3.141=0
  - libcurand-dev=10.3.3.141=0
  - libcusolver=11.3.4.124=h33c3c4e_0
  - libcusparse=11.7.2.124=h7538f96_0
  - libcusparse-dev=11.7.2.124=hbbe9722_0
  - libdeflate=1.18=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=13.2.0=h807b86a_0
  - libgcrypt=1.10.1=h166bdaf_0
  - libgfortran-ng=13.2.0=h69a702a_0
  - libgfortran5=13.2.0=ha4646dd_0
  - libglib=2.78.0=hebfc3b9_0
  - libgomp=13.2.0=h807b86a_0
  - libgpg-error=1.47=h71f35ed_0
  - libgrpc=1.57.0=ha4d0f93_1
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=2.1.5.1=hd590300_1
  - liblapack=3.9.0=16_linux64_mkl
  - libllvm14=14.0.6=hcd5def8_4
  - libllvm15=15.0.7=h5cf9203_3
  - libnpp=11.6.3.124=hd2722f0_0
  - libnpp-dev=11.6.3.124=h3c42840_0
  - libnsl=2.0.0=h7f98852_0
  - libnvjpeg=11.6.2.124=hd473ad6_0
  - libnvjpeg-dev=11.6.2.124=hb5906b9_0
  - libogg=1.3.4=h7f98852_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h753d276_0
  - libpq=15.4=hfc447b1_0
  - libprotobuf=4.23.4=hf27288f_6
  - libsndfile=1.2.2=hbc2eb40_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.43.0=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_0
  - libsystemd0=254=h3516f8a_0
  - libtiff=4.5.1=h8b53f26_1
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.3.1=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxkbcommon=1.5.0=h5d7e998_3
  - libxml2=2.11.5=h232c23b_1
  - libzlib=1.2.13=hd590300_5
  - llvmlite=0.40.1=py39h174d805_0
  - lz4-c=1.9.4=hcb278e6_0
  - markdown=3.4.4=pyhd8ed1ab_0
  - markupsafe=2.1.3=py39hd1e30aa_0
  - matplotlib=3.7.2=py39hf3d152e_0
  - matplotlib-base=3.7.2=py39h0126182_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=0.8.4=py39h27cfd23_1000
  - mkl=2022.1.0=hc2b9512_224
  - monty=2023.9.5=pyhd8ed1ab_0
  - mp-api=0.36.1=pyhd8ed1ab_0
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.0=hb012696_0
  - mpg123=1.31.3=hcb278e6_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msgpack-python=1.0.5=py39h4b4f3f3_0
  - multidict=6.0.4=py39h72bdee0_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - mysql-common=8.0.33=hf1915f5_4
  - mysql-libs=8.0.33=hca2cd23_4
  - nbclassic=0.5.5=py39h06a4308_0
  - nbconvert=5.5.0=py_0
  - nbformat=5.7.0=py39h06a4308_0
  - ncurses=6.4=hcb278e6_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - networkx=3.1=pyhd8ed1ab_0
  - nodeenv=1.8.0=pyhd8ed1ab_0
  - notebook=6.5.4=py39h06a4308_1
  - notebook-shim=0.2.2=py39h06a4308_0
  - nsight-compute=2023.2.2.3=0
  - nspr=4.35=h27087fc_0
  - nss=3.92=h1d7d5a4_0
  - numba=0.57.1=py39hb75a051_0
  - numpy=1.24.4=py39h6183b62_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.2=hd590300_0
  - opt-einsum=3.0.0=py_0
  - opt_einsum_fx=0.1.4=pyhd8ed1ab_0
  - orjson=3.9.6=py39h10b2342_0
  - packaging=23.1=pyhd8ed1ab_0
  - palettable=3.3.3=pyhd8ed1ab_0
  - pandas=2.1.0=py39hddac248_0
  - pandoc=2.12=h06a4308_3
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.11.2=pyhd8ed1ab_0
  - pathtools=0.1.2=py_1
  - pcre2=10.40=hc3806b6_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=10.0.0=py39haaeba84_0
  - pip=23.2.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - platformdirs=3.10.0=pyhd8ed1ab_0
  - plotly=5.16.1=pyhd8ed1ab_0
  - pluggy=1.3.0=pyhd8ed1ab_0
  - ply=3.11=py_1
  - pooch=1.7.0=pyha770c72_3
  - pre-commit=2.10.1=py39hf3d152e_0
  - prometheus_client=0.14.1=py39h06a4308_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - protobuf=4.23.4=py39h60f6b12_2
  - psutil=5.9.5=py39h72bdee0_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulseaudio-client=16.1=hb77b528_5
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pybtex=0.24.0=pyhd8ed1ab_2
  - pycparser=2.21=pyhd8ed1ab_0
  - pydantic=1.10.12=py39hd1e30aa_1
  - pyg=2.2.0=py39_torch_1.13.0_cu116
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_0
  - pymatgen=2023.5.10=py39hf86192f_0
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.9=py39h52134e7_4
  - pyqt5-sip=12.12.2=py39h3d6467e_4
  - pyrsistent=0.18.0=py39heee7806_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=7.4.2=pyhd8ed1ab_0
  - python=3.9.18=h0755675_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=py39h06a4308_0
  - python-lmdb=1.4.1=py39h227be39_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.9=3_cp39
  - pytorch=1.13.1=py3.9_cuda11.6_cudnn8.3.2_0
  - pytorch-cluster=1.6.0=py39_torch_1.13.0_cu116
  - pytorch-cuda=11.6=h867d48c_1
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.1.0=py39_torch_1.13.0_cu116
  - pytorch-sparse=0.6.15=py39_torch_1.13.0_cu116
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0.1=py39hd1e30aa_0
  - pyzmq=23.2.0=py39h6a678d5_0
  - qt-main=5.15.8=hc47bfe8_16
  - qtconsole=5.4.2=py39h06a4308_0
  - qtpy=2.2.0=py39h06a4308_0
  - re2=2023.03.02=h8c504da_0
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - ruamel.yaml=0.17.32=py39hd1e30aa_0
  - ruamel.yaml.clib=0.2.7=py39h72bdee0_1
  - s3transfer=0.6.2=pyhd8ed1ab_0
  - scikit-learn=1.3.0=py39hc236052_0
  - scipy=1.11.2=py39h6183b62_0
  - seaborn=0.12.2=py39h06a4308_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - sentry-sdk=1.30.0=pyhd8ed1ab_0
  - setproctitle=1.3.2=py39hb9d737c_1
  - setuptools=68.2.2=pyhd8ed1ab_0
  - sip=6.7.11=py39h3d6467e_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - sniffio=1.2.0=py39h06a4308_1
  - spglib=2.0.2=py39h389d5f1_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - submitit=1.4.5=pyhd8ed1ab_0
  - sympy=1.12=pypyh9d50eac_103
  - syrupy=3.0.6=pyhd8ed1ab_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tenacity=8.2.3=pyhd8ed1ab_0
  - tensorboard=2.14.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py39h079d5ae_0
  - terminado=0.17.1=py39h06a4308_0
  - testpath=0.6.0=py39h06a4308_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.3.3=py39hd1e30aa_0
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typed-ast=1.5.5=py39hd1e30aa_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - ukkonen=1.0.1=py39hf939315_3
  - uncertainties=3.1.7=pyhd8ed1ab_0
  - unicodedata2=15.0.0=py39hb9d737c_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - virtualenv=20.24.4=pyhd8ed1ab_0
  - wandb=0.15.10=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py39h06a4308_1
  - websocket-client=0.58.0=py39h06a4308_4
  - werkzeug=2.3.7=pyhd8ed1ab_0
  - wheel=0.41.2=pyhd8ed1ab_0
  - widgetsnbextension=4.0.5=py39h06a4308_0
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.39=hd590300_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.6=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.2=py39hd1e30aa_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - ijson==3.2.3
      - pynndescent==0.5.10
      - pyside6==6.6.0
      - pyside6-addons==6.6.0
      - pyside6-essentials==6.6.0
      - shiboken6==6.6.0
      - tbb==2021.10.0
      - traits==6.4.3
      - umap-learn==0.5.4
prefix: /home/yangzd/miniconda3/envs/ocp-models
